[package]
name = "codewars_rust"
version = "0.1.0"
authors = ["Matt Aschmann <matt.aschmann@gmail.com>"]

[dependencies]
chrono = "0.4.9"
itertools = "0.8.1"
regex = "1.3.1"
time-test = "0.2.2"
num = "0.2.0"
common_macros = "0.1.1"
